services:
  - type: web
    name: ai-outfit-suggester
    env: node
    buildCommand: npm run install-all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: GEMINI_API_KEY
        sync: false
    staticPublishPath: ./frontend/build 